<?php

function nzfoverzicht_menu() {
	$items = array();

	$items['nationaal-zorgfonds-overzicht'] = array(
		'title' => t('Nationaal ZorgFonds Overzicht'),
		'page callback' => 'nzfoverzicht_page',
		'access callback' => 'user_is_logged_in',
		'description' => t('Nationaal ZorgFonds Overzicht'),
		'type' => MENU_CALLBACK,
    'file' => 'nzfoverzicht.inc',
	);

  $items['nationaal-zorgfonds-detail'] = array(
    'title' => t('Nationaal ZorgFonds Detail'),
    'page callback' => 'nzfdetail_page',
    'access callback' => 'user_is_logged_in',
    'description' => t('Nationaal ZorgFonds Detail'),
    'type' => MENU_CALLBACK,
    'file' => 'nzfdetail.inc',
  );

	return $items;
}

